version: '3.3'
services:
  back:
    build: ./back-end
    container_name: back-end
    stdin_open: true
    tty: true
    restart: on-failure
    ports:
      - 3002:3002
    volumes:
      - ./back-end:/app/back-end
    command: dev
    env_file:
      - ./back-end/.env
#  Redundância para facilitar a lentura e identificação das variáveis necessárias
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - HOSTNAME=${HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - PORT=${PORT}
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:8.0.23
    restart: on-failure
    ports:
      - 3306:3306
    
    environment:
      - MYSQL_ROOT_PASSWORD=181216
      - MYSQL_PASSWORD=181216

    volumes:
      - database:/var/lib/mysql
volumes:
  database:
