version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.23
    restart: on-failure
    ports:
      - 3306:3306
    
    environment:
      - MYSQL_ROOT_PASSWORD=181216
      - MYSQL_PASSWORD=181216
      - MYSQL_USER=root

    volumes:
      - database:/var/lib/mysql
volumes:
  database:
