'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      'livros',
      [
        {
          idColecao: 2,
          nomeLivro: 'A Sociedade do Anel',
          idAutor: 1,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 2,
          nomeLivro: 'As Duas Torres',
          idAutor: 1,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 2,
          nomeLivro: 'O Retorno do Rei',
          idAutor: 1,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 6,
          nomeLivro: 'O Arqueiro',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 6,
          nomeLivro: 'O Andarilho',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 6,
          nomeLivro: 'O Herege',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 6,
          nomeLivro: '1356',
          idAutor: 2,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 5,
          nomeLivro: 'O Rei do Inverno',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 5,
          nomeLivro: 'O Inimigo de Deus',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 5,
          nomeLivro: 'Excalibur',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'O Último Reino',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'O Cavaleiro da Morte',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'Os Senhores do Norte',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'A Canção da Espada',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'Terra em Chamas',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'Morte dos Reis',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'O Guerreiro Pagão',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'O Trono Vazio',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'Guerreiros da Tempestade',
          idAutor: 2,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'O Portador do Fogo',
          idAutor: 2,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'A Guerra do Lobo',
          idAutor: 2,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'A Espada dos Reis',
          idAutor: 2,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 8,
          nomeLivro: 'O Senhor da Guerra',
          idAutor: 2,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 7,
          nomeLivro: 'A Fortaleza de Sharpe',
          idAutor: 2,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 13,
          nomeLivro: 'O Filho da Luz',
          idAutor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 5,
        },
        {
          idColecao: 13,
          nomeLivro: 'O Templo de Milhões de Anos',
          idAutor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 5,
        },
        {
          idColecao: 13,
          nomeLivro: 'A Batalha de Kadesh',
          idAutor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 5,
        },
        {
          idColecao: 13,
          nomeLivro: 'A Dama de Abu-Simbel',
          idAutor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 5,
        },
        {
          idColecao: 13,
          nomeLivro: 'Sob a Acácia do Ocidente',
          idAutor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 5,
        },
        {
          idColecao: 14,
          nomeLivro: 'Nefer, o Silencioso',
          idAutor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 5,
        },
        {
          idColecao: 14,
          nomeLivro: 'A Mulher Sábia',
          idAutor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 5,
        },
        {
          idColecao: 14,
          nomeLivro: 'Paneb, o Ardoroso',
          idAutor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 5,
        },
        {
          idColecao: 14,
          nomeLivro: 'O Lugar da Verdade',
          idAutor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 5,
        },
        {
          idColecao: 3,
          nomeLivro: 'O Lobo das Planicies',
          idAutor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 3,
          nomeLivro: 'Os Senhores do Arco ',
          idAutor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 3,
          nomeLivro: 'Os Ossos das Colinas',
          idAutor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 3,
          nomeLivro: 'Império da Prata',
          idAutor: 4,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 3,
          nomeLivro: 'Conquistador',
          idAutor: 4,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 4,
          nomeLivro: 'Os Portões de Roma ',
          idAutor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 4,
          nomeLivro: 'A Morte dos Reis',
          idAutor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 4,
          nomeLivro: 'Campo de Espadas',
          idAutor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 4,
          nomeLivro: 'Os Deuses da Guerra',
          idAutor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 4,
          nomeLivro: 'Sangue dos Deuses',
          idAutor: 4,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 12,
          nomeLivro: 'A magia da alvorada',
          idAutor: 11,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 12,
          nomeLivro: 'A Magia do Anoitecer',
          idAutor: 11,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 12,
          nomeLivro: 'A Magia da Aurora',
          idAutor: 11,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 19,
          nomeLivro: 'Aprendiz',
          idAutor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 19,
          nomeLivro: 'Mestre',
          idAutor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 19,
          nomeLivro: 'Espinho de Prata',
          idAutor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 19,
          nomeLivro: 'As Trevas de Sethanon',
          idAutor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 20,
          nomeLivro: 'A Filha do Império',
          idAutor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 20,
          nomeLivro: 'A Serva do Império',
          idAutor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 20,
          nomeLivro: 'A senhora do império',
          idAutor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 11,
          nomeLivro: 'Renascença',
          idAutor: 9,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 3,
        },
        {
          idColecao: 11,
          nomeLivro: 'Irmandade',
          idAutor: 9,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 3,
        },
        {
          idColecao: 11,
          nomeLivro: 'A Cruzada Secreta',
          idAutor: 9,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 3,
        },
        {
          idColecao: 11,
          nomeLivro: 'Revelações',
          idAutor: 9,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 3,
        },
        {
          idColecao: 11,
          nomeLivro: 'Renegado',
          idAutor: 9,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 3,
        },
        {
          idColecao: 11,
          nomeLivro: 'Bandeira Negra',
          idAutor: 9,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 3,
        },
        {
          idColecao: 11,
          nomeLivro: 'União',
          idAutor: 9,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 3,
        },
        {
          idColecao: 11,
          nomeLivro: 'Submundo',
          idAutor: 9,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 3,
        },
        {
          idColecao: 11,
          nomeLivro: 'Juramento do Deserto',
          idAutor: 9,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 3,
        },
        {
          idColecao: 15,
          nomeLivro: 'Eragon',
          idAutor: 8,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 15,
          nomeLivro: 'Eldest',
          idAutor: 8,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 15,
          nomeLivro: 'Brisingr',
          idAutor: 8,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 15,
          nomeLivro: 'Herança',
          idAutor: 8,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 15,
          nomeLivro: 'O garfo, a bruxa e o dragão',
          idAutor: 8,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 9,
          nomeLivro: 'Jogos Vorazes',
          idAutor: 13,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 9,
          nomeLivro: 'Em Chamas',
          idAutor: 13,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 9,
          nomeLivro: 'A Esperança',
          idAutor: 13,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 9,
          nomeLivro: 'A Cantiga dos pássaros e das serpentes',
          idAutor: 13,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 26,
          nomeLivro: 'A Maldição do Tigre',
          idAutor: 20,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 26,
          nomeLivro: 'O Resgate do Tigre',
          idAutor: 20,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 26,
          nomeLivro: 'A Viagem do Tigre',
          idAutor: 20,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 26,
          nomeLivro: 'O Destino do Tigre',
          idAutor: 20,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 26,
          nomeLivro: 'A Promessa do Tigre',
          idAutor: 20,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 26,
          nomeLivro: 'O Sonho do Tigre',
          idAutor: 20,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 25,
          nomeLivro: 'O Nome do Vento',
          idAutor: 7,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 25,
          nomeLivro: 'O Temor do Sábio',
          idAutor: 7,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 25,
          nomeLivro: 'Doors of Stone',
          idAutor: 7,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 6,
        },
        {
          idColecao: 18,
          nomeLivro: 'A Senhora da Magia',
          idAutor: 14,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 16,
        },
        {
          idColecao: 18,
          nomeLivro: 'A Grande Rainha',
          idAutor: 14,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 16,
        },
        {
          idColecao: 18,
          nomeLivro: 'O Gamo-Rei',
          idAutor: 14,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 16,
        },
        {
          idColecao: 18,
          nomeLivro: 'O Prisioneiro da Árvore',
          idAutor: 14,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 16,
        },
        {
          idColecao: 10,
          nomeLivro: 'Pedra Filosofal',
          idAutor: 6,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 10,
          nomeLivro: 'Câmara Secreta',
          idAutor: 6,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 10,
          nomeLivro: 'Prisioneiro de Azkaban',
          idAutor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 10,
          nomeLivro: 'Cálice de Fogo',
          idAutor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 10,
          nomeLivro: 'Ordem da Fênix',
          idAutor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 10,
          nomeLivro: 'Enigma do Príncipe',
          idAutor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 10,
          nomeLivro: 'Relíquias da Morte',
          idAutor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 10,
          nomeLivro: 'Criança Amaldiçoada',
          idAutor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 8,
        },
        {
          idColecao: 27,
          nomeLivro: 'O Sonho de Olympias',
          idAutor: 15,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 8,
        },
        {
          idColecao: 27,
          nomeLivro: 'As areias de Ammon',
          idAutor: 15,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 8,
        },
        {
          idColecao: 27,
          nomeLivro: 'Os Confins do Mundo',
          idAutor: 15,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 8,
        },
        {
          idColecao: 16,
          nomeLivro: 'O Último Desejo',
          idAutor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 16,
          nomeLivro: 'A Espada do Destino',
          idAutor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 16,
          nomeLivro: 'O Sangue dos Elfos',
          idAutor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 16,
          nomeLivro: 'Tempo do Desprezo',
          idAutor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 16,
          nomeLivro: 'Batismo de Fogo',
          idAutor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 16,
          nomeLivro: 'A Torre da Andorinha',
          idAutor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 16,
          nomeLivro: 'A Senhora do Lago',
          idAutor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 16,
          nomeLivro: 'Tempo de Tempestade',
          idAutor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 22,
          nomeLivro: 'Dragões do Crepúsculo do Outono',
          idAutor: 16,
          tenho: 0,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 13,
        },
        {
          idColecao: 22,
          nomeLivro: 'Dragões da Noite de Inverno',
          idAutor: 16,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 13,
        },
        {
          idColecao: 22,
          nomeLivro: 'Dragões do Alvorecer da Primavera',
          idAutor: 16,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 13,
        },
        {
          idColecao: 22,
          nomeLivro: 'Dragões de Uma Chama de Verão',
          idAutor: 16,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 13,
        },
        {
          idColecao: 24,
          nomeLivro: 'A Guerra dos Tronos',
          idAutor: 5,
          tenho: 0,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 24,
          nomeLivro: 'A Fúria dos Reis',
          idAutor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 24,
          nomeLivro: 'A Senhora do Lago',
          idAutor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 24,
          nomeLivro: 'A Tormenta de Espadas',
          idAutor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 24,
          nomeLivro: 'O Festim dos Corvos',
          idAutor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 24,
          nomeLivro: 'A Dança dos Dragões',
          idAutor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 24,
          nomeLivro: 'Os Ventos do Inverno',
          idAutor: 5,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 28,
          nomeLivro: 'A Espada de Shannara',
          idAutor: 17,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 7,
        },
        {
          idColecao: 28,
          nomeLivro: 'As Pedras Élficas de Shannara',
          idAutor: 17,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 7,
        },
        {
          idColecao: 28,
          nomeLivro: 'A Canção de Shannara',
          idAutor: 17,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 7,
        },
        {
          idColecao: 23,
          nomeLivro: 'Caçadores de Bruxas',
          idAutor: 19,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 23,
          nomeLivro: 'Corações de Neve',
          idAutor: 19,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 23,
          nomeLivro: 'Círculos de Chuva',
          idAutor: 19,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 29,
          nomeLivro: 'God Of War (vol. 1 )',
          idAutor: 29,
          tenho: 1,
          lido: 1,
          nota: 6,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 29,
          nomeLivro: 'God Of War (vol. 2 )',
          idAutor: 29,
          tenho: 1,
          lido: 1,
          nota: 6,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 30,
          nomeLivro: 'A Espada na Pedra',
          idAutor: 21,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 17,
        },
        {
          idColecao: 30,
          nomeLivro: 'A Rainha do Ar e das Sombras',
          idAutor: 21,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 17,
        },
        {
          idColecao: 30,
          nomeLivro: 'O Cavaleiro Imperfeito',
          idAutor: 21,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 17,
        },
        {
          idColecao: 30,
          nomeLivro: 'A Chama ao Vento',
          idAutor: 21,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 17,
        },
        {
          idColecao: 30,
          nomeLivro: 'O Livro de Merlin',
          idAutor: 21,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 17,
        },
        {
          idColecao: 31,
          nomeLivro: 'O Primeiro Guerreiro',
          idAutor: 22,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 11,
        },
        {
          idColecao: 31,
          nomeLivro: 'O Guerreiro de Deus',
          idAutor: 22,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 11,
        },
        {
          idColecao: 31,
          nomeLivro: 'As Cruzadas de 2020',
          idAutor: 22,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 11,
        },
        {
          idColecao: 32,
          nomeLivro: 'Herdeiros de Atlântida',
          idAutor: 27,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 32,
          nomeLivro: 'Anjos da Morte',
          idAutor: 27,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 32,
          nomeLivro: 'Paraíso Perdido',
          idAutor: 27,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 33,
          nomeLivro: 'As Mentiras de Locke Lamora',
          idAutor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 33,
          nomeLivro: 'Mares de Sangue',
          idAutor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 33,
          nomeLivro: 'República de Ladrões',
          idAutor: 24,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 33,
          nomeLivro: 'The Thorn of Emberlain ',
          idAutor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 33,
          nomeLivro: 'The Ministry of Necessity',
          idAutor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 33,
          nomeLivro: 'The Mage and the Master Spy',
          idAutor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 33,
          nomeLivro: 'Inherit the Night',
          idAutor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 12,
        },
        {
          idColecao: 34,
          nomeLivro: 'A Canção do Sangue',
          idAutor: 23,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 34,
          nomeLivro: 'O Senhor da Torre',
          idAutor: 23,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 34,
          nomeLivro: 'A Rainha do Fogo',
          idAutor: 23,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 35,
          nomeLivro: 'A Ordem',
          idAutor: 31,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 4,
        },
        {
          idColecao: 35,
          nomeLivro: 'Tempestade de Luz',
          idAutor: 31,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 4,
        },
        {
          idColecao: 35,
          nomeLivro: 'Livro de Cain',
          idAutor: 31,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 4,
        },
        {
          idColecao: 35,
          nomeLivro: 'Livro de Tyrael',
          idAutor: 31,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 4,
        },
        {
          idColecao: 36,
          nomeLivro: 'Uma Nova Esperança',
          idAutor: 28,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 36,
          nomeLivro: 'Império Contra-Ataca',
          idAutor: 28,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 36,
          nomeLivro: 'O Retorno de Jedi',
          idAutor: 28,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 37,
          nomeLivro: 'O Sobrinho do Mago ',
          idAutor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 37,
          nomeLivro: 'O Leão, A Feiticeira e o Guarda-roupa',
          idAutor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 37,
          nomeLivro: 'O Cavalo e seu Menino',
          idAutor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 37,
          nomeLivro: 'O Príncipe Caspian',
          idAutor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 37,
          nomeLivro: 'A Viagem do Peregrino da Alvorada',
          idAutor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 37,
          nomeLivro: 'A Cadeira de Prata',
          idAutor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 37,
          nomeLivro: 'A Última Batalha',
          idAutor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          idCategoria: 3,
          idEditora: 15,
        },
        {
          idColecao: 38,
          nomeLivro: 'A Cor da Magia',
          idAutor: 37,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 1,
          idEditora: 10,
        },
        {
          idColecao: 1,
          nomeLivro: 'A Queda De Artur',
          idAutor: 1,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 1,
          nomeLivro: 'A Lenda de Sigurd e Gudrún',
          idAutor: 1,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 1,
          nomeLivro: 'Mestre Gil de Ham',
          idAutor: 1,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 1,
          nomeLivro: 'Roverandom',
          idAutor: 1,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 1,
          nomeLivro: 'Contos inacabados',
          idAutor: 1,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 1,
          nomeLivro: 'As Cartas de J. R. R. Tolkien',
          idAutor: 1,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 1,
          nomeLivro: 'O Silmarillion',
          idAutor: 1,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 1,
          nomeLivro: 'O Hobbit',
          idAutor: 1,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 1,
        },
        {
          idColecao: 1,
          nomeLivro: 'Atlantis',
          idAutor: 26,
          tenho: 1,
          lido: 1,
          nota: 7,
          idCategoria: 2,
          idEditora: 11,
        },
        {
          idColecao: 1,
          nomeLivro: 'O Coração Dos Heróis',
          idAutor: 25,
          tenho: 1,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 2,
        },
        {
          idColecao: 1,
          nomeLivro: 'Jogador Nº 1',
          idAutor: 32,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 3,
          idEditora: 2,
        },
        {
          idColecao: 1,
          nomeLivro: 'Ruas Estranhas',
          idAutor: 5,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 3,
          idEditora: 2,
        },
        {
          idColecao: 1,
          nomeLivro: 'Os Pilares da Terra',
          idAutor: 33,
          tenho: 1,
          lido: 1,
          nota: 8,
          idCategoria: 2,
          idEditora: 8,
        },
        {
          idColecao: 1,
          nomeLivro: 'Stonehenge',
          idAutor: 2,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 3,
        },
        {
          idColecao: 1,
          nomeLivro: 'O Mundo Magico Do Senhor Dos Aneis',
          idAutor: 34,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 1,
          idEditora: 18,
        },
        {
          idColecao: 1,
          nomeLivro: 'Os Filhos de Húrin',
          idAutor: 1,
          tenho: 1,
          lido: 1,
          nota: 9,
          idCategoria: 1,
          idEditora: 9,
        },
        {
          idColecao: 1,
          nomeLivro: 'Fora de Controle',
          idAutor: 36,
          tenho: 0,
          lido: 0,
          nota: 0,
          idCategoria: 2,
          idEditora: 19,
        },
      ],
      {}
    );
    {
      timestamps: false;
    }
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('livros', null, {});
  },
};
