module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      'livros',
      [
        {
          id_colecao: 2,
          nome: 'A Sociedade do Anel',
          id_autor: 1,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 2,
          nome: 'As Duas Torres',
          id_autor: 1,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 2,
          nome: 'O Retorno do Rei',
          id_autor: 1,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 6,
          nome: 'O Arqueiro',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 6,
          nome: 'O Andarilho',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 6,
          nome: 'O Herege',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 6,
          nome: '1356',
          id_autor: 2,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 5,
          nome: 'O Rei do Inverno',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 5,
          nome: 'O Inimigo de Deus',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 5,
          nome: 'Excalibur',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'O Último Reino',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'O Cavaleiro da Morte',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'Os Senhores do Norte',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'A Canção da Espada',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'Terra em Chamas',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'Morte dos Reis',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'O Guerreiro Pagão',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'O Trono Vazio',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'Guerreiros da Tempestade',
          id_autor: 2,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'O Portador do Fogo',
          id_autor: 2,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'A Guerra do Lobo',
          id_autor: 2,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'A Espada dos Reis',
          id_autor: 2,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 8,
          nome: 'O Senhor da Guerra',
          id_autor: 2,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 7,
          nome: 'A Fortaleza de Sharpe',
          id_autor: 2,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 13,
          nome: 'O Filho da Luz',
          id_autor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 5,
        },
        {
          id_colecao: 13,
          nome: 'O Templo de Milhões de Anos',
          id_autor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 5,
        },
        {
          id_colecao: 13,
          nome: 'A Batalha de Kadesh',
          id_autor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 5,
        },
        {
          id_colecao: 13,
          nome: 'A Dama de Abu-Simbel',
          id_autor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 5,
        },
        {
          id_colecao: 13,
          nome: 'Sob a Acácia do Ocidente',
          id_autor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 5,
        },
        {
          id_colecao: 14,
          nome: 'Nefer, o Silencioso',
          id_autor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 5,
        },
        {
          id_colecao: 14,
          nome: 'A Mulher Sábia',
          id_autor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 5,
        },
        {
          id_colecao: 14,
          nome: 'Paneb, o Ardoroso',
          id_autor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 5,
        },
        {
          id_colecao: 14,
          nome: 'O Lugar da Verdade',
          id_autor: 3,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 5,
        },
        {
          id_colecao: 3,
          nome: 'O Lobo das Planicies',
          id_autor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 3,
          nome: 'Os Senhores do Arco ',
          id_autor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 3,
          nome: 'Os Ossos das Colinas',
          id_autor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 3,
          nome: 'Império da Prata',
          id_autor: 4,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 3,
          nome: 'Conquistador',
          id_autor: 4,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 4,
          nome: 'Os Portões de Roma ',
          id_autor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 4,
          nome: 'A Morte dos Reis',
          id_autor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 4,
          nome: 'Campo de Espadas',
          id_autor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 4,
          nome: 'Os Deuses da Guerra',
          id_autor: 4,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 4,
          nome: 'Sangue dos Deuses',
          id_autor: 4,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 12,
          nome: 'A magia da alvorada',
          id_autor: 11,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 12,
          nome: 'A Magia do Anoitecer',
          id_autor: 11,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 12,
          nome: 'A Magia da Aurora',
          id_autor: 11,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 19,
          nome: 'Aprendiz',
          id_autor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 19,
          nome: 'Mestre',
          id_autor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 19,
          nome: 'Espinho de Prata',
          id_autor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 19,
          nome: 'As Trevas de Sethanon',
          id_autor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 20,
          nome: 'A Filha do Império',
          id_autor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 20,
          nome: 'A Serva do Império',
          id_autor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 20,
          nome: 'A senhora do império',
          id_autor: 12,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 11,
          nome: 'Renascença',
          id_autor: 9,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 3,
        },
        {
          id_colecao: 11,
          nome: 'Irmandade',
          id_autor: 9,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 3,
        },
        {
          id_colecao: 11,
          nome: 'A Cruzada Secreta',
          id_autor: 9,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 3,
        },
        {
          id_colecao: 11,
          nome: 'Revelações',
          id_autor: 9,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 3,
        },
        {
          id_colecao: 11,
          nome: 'Renegado',
          id_autor: 9,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 3,
        },
        {
          id_colecao: 11,
          nome: 'Bandeira Negra',
          id_autor: 9,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 3,
        },
        {
          id_colecao: 11,
          nome: 'União',
          id_autor: 9,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 3,
        },
        {
          id_colecao: 11,
          nome: 'Submundo',
          id_autor: 9,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 3,
        },
        {
          id_colecao: 11,
          nome: 'Juramento do Deserto',
          id_autor: 9,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 3,
        },
        {
          id_colecao: 15,
          nome: 'Eragon',
          id_autor: 8,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 15,
          nome: 'Eldest',
          id_autor: 8,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 15,
          nome: 'Brisingr',
          id_autor: 8,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 15,
          nome: 'Herança',
          id_autor: 8,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 15,
          nome: 'O garfo, a bruxa e o dragão',
          id_autor: 8,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 9,
          nome: 'Jogos Vorazes',
          id_autor: 13,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 9,
          nome: 'Em Chamas',
          id_autor: 13,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 9,
          nome: 'A Esperança',
          id_autor: 13,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 9,
          nome: 'A Cantiga dos pássaros e das serpentes',
          id_autor: 13,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 26,
          nome: 'A Maldição do Tigre',
          id_autor: 20,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 26,
          nome: 'O Resgate do Tigre',
          id_autor: 20,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 26,
          nome: 'A Viagem do Tigre',
          id_autor: 20,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 26,
          nome: 'O Destino do Tigre',
          id_autor: 20,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 26,
          nome: 'A Promessa do Tigre',
          id_autor: 20,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 26,
          nome: 'O Sonho do Tigre',
          id_autor: 20,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 25,
          nome: 'O Nome do Vento',
          id_autor: 7,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 25,
          nome: 'O Temor do Sábio',
          id_autor: 7,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 25,
          nome: 'Doors of Stone',
          id_autor: 7,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 6,
        },
        {
          id_colecao: 18,
          nome: 'A Senhora da Magia',
          id_autor: 14,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 16,
        },
        {
          id_colecao: 18,
          nome: 'A Grande Rainha',
          id_autor: 14,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 16,
        },
        {
          id_colecao: 18,
          nome: 'O Gamo-Rei',
          id_autor: 14,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 16,
        },
        {
          id_colecao: 18,
          nome: 'O Prisioneiro da Árvore',
          id_autor: 14,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 16,
        },
        {
          id_colecao: 10,
          nome: 'Pedra Filosofal',
          id_autor: 6,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 10,
          nome: 'Câmara Secreta',
          id_autor: 6,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 10,
          nome: 'Prisioneiro de Azkaban',
          id_autor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 10,
          nome: 'Cálice de Fogo',
          id_autor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 10,
          nome: 'Ordem da Fênix',
          id_autor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 10,
          nome: 'Enigma do Príncipe',
          id_autor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 10,
          nome: 'Relíquias da Morte',
          id_autor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 10,
          nome: 'Criança Amaldiçoada',
          id_autor: 6,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 8,
        },
        {
          id_colecao: 27,
          nome: 'O Sonho de Olympias',
          id_autor: 15,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 8,
        },
        {
          id_colecao: 27,
          nome: 'As areias de Ammon',
          id_autor: 15,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 8,
        },
        {
          id_colecao: 27,
          nome: 'Os Confins do Mundo',
          id_autor: 15,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 8,
        },
        {
          id_colecao: 16,
          nome: 'O Último Desejo',
          id_autor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 16,
          nome: 'A Espada do Destino',
          id_autor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 16,
          nome: 'O Sangue dos Elfos',
          id_autor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 16,
          nome: 'Tempo do Desprezo',
          id_autor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 16,
          nome: 'Batismo de Fogo',
          id_autor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 16,
          nome: 'A Torre da Andorinha',
          id_autor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 16,
          nome: 'A Senhora do Lago',
          id_autor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 16,
          nome: 'Tempo de Tempestade',
          id_autor: 10,
          tenho: 1,
          lido: 1,
          nota: 10,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 22,
          nome: 'Dragões do Crepúsculo do Outono',
          id_autor: 16,
          tenho: 0,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 13,
        },
        {
          id_colecao: 22,
          nome: 'Dragões da Noite de Inverno',
          id_autor: 16,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 13,
        },
        {
          id_colecao: 22,
          nome: 'Dragões do Alvorecer da Primavera',
          id_autor: 16,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 13,
        },
        {
          id_colecao: 22,
          nome: 'Dragões de Uma Chama de Verão',
          id_autor: 16,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 13,
        },
        {
          id_colecao: 24,
          nome: 'A Guerra dos Tronos',
          id_autor: 5,
          tenho: 0,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 24,
          nome: 'A Fúria dos Reis',
          id_autor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 24,
          nome: 'A Senhora do Lago',
          id_autor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 24,
          nome: 'A Tormenta de Espadas',
          id_autor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 24,
          nome: 'O Festim dos Corvos',
          id_autor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 24,
          nome: 'A Dança dos Dragões',
          id_autor: 5,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 24,
          nome: 'Os Ventos do Inverno',
          id_autor: 5,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 28,
          nome: 'A Espada de Shannara',
          id_autor: 17,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 7,
        },
        {
          id_colecao: 28,
          nome: 'As Pedras Élficas de Shannara',
          id_autor: 17,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 7,
        },
        {
          id_colecao: 28,
          nome: 'A Canção de Shannara',
          id_autor: 17,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 7,
        },
        {
          id_colecao: 23,
          nome: 'Caçadores de Bruxas',
          id_autor: 19,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 23,
          nome: 'Corações de Neve',
          id_autor: 19,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 23,
          nome: 'Círculos de Chuva',
          id_autor: 19,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 29,
          nome: 'God Of War (vol. 1 )',
          id_autor: 29,
          tenho: 1,
          lido: 1,
          nota: 6,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 29,
          nome: 'God Of War (vol. 2 )',
          id_autor: 29,
          tenho: 1,
          lido: 1,
          nota: 6,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 30,
          nome: 'A Espada na Pedra',
          id_autor: 21,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 17,
        },
        {
          id_colecao: 30,
          nome: 'A Rainha do Ar e das Sombras',
          id_autor: 21,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 17,
        },
        {
          id_colecao: 30,
          nome: 'O Cavaleiro Imperfeito',
          id_autor: 21,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 17,
        },
        {
          id_colecao: 30,
          nome: 'A Chama ao Vento',
          id_autor: 21,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 17,
        },
        {
          id_colecao: 30,
          nome: 'O Livro de Merlin',
          id_autor: 21,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 17,
        },
        {
          id_colecao: 31,
          nome: 'O Primeiro Guerreiro',
          id_autor: 22,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 11,
        },
        {
          id_colecao: 31,
          nome: 'O Guerreiro de Deus',
          id_autor: 22,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 11,
        },
        {
          id_colecao: 31,
          nome: 'As Cruzadas de 2020',
          id_autor: 22,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 11,
        },
        {
          id_colecao: 32,
          nome: 'Herdeiros de Atlântida',
          id_autor: 27,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 32,
          nome: 'Anjos da Morte',
          id_autor: 27,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 32,
          nome: 'Paraíso Perdido',
          id_autor: 27,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 33,
          nome: 'As Mentiras de Locke Lamora',
          id_autor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 33,
          nome: 'Mares de Sangue',
          id_autor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 33,
          nome: 'República de Ladrões',
          id_autor: 24,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 33,
          nome: 'The Thorn of Emberlain ',
          id_autor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 33,
          nome: 'The Ministry of Necessity',
          id_autor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 33,
          nome: 'The Mage and the Master Spy',
          id_autor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 33,
          nome: 'Inherit the Night',
          id_autor: 24,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 12,
        },
        {
          id_colecao: 34,
          nome: 'A Canção do Sangue',
          id_autor: 23,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 34,
          nome: 'O Senhor da Torre',
          id_autor: 23,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 34,
          nome: 'A Rainha do Fogo',
          id_autor: 23,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 35,
          nome: 'A Ordem',
          id_autor: 31,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 4,
        },
        {
          id_colecao: 35,
          nome: 'Tempestade de Luz',
          id_autor: 31,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 4,
        },
        {
          id_colecao: 35,
          nome: 'Livro de Cain',
          id_autor: 31,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 4,
        },
        {
          id_colecao: 35,
          nome: 'Livro de Tyrael',
          id_autor: 31,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 4,
        },
        {
          id_colecao: 36,
          nome: 'Uma Nova Esperança',
          id_autor: 28,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 36,
          nome: 'Império Contra-Ataca',
          id_autor: 28,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 36,
          nome: 'O Retorno de Jedi',
          id_autor: 28,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 37,
          nome: 'O Sobrinho do Mago ',
          id_autor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 37,
          nome: 'O Leão, A Feiticeira e o Guarda-roupa',
          id_autor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 37,
          nome: 'O Cavalo e seu Menino',
          id_autor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 37,
          nome: 'O Príncipe Caspian',
          id_autor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 37,
          nome: 'A Viagem do Peregrino da Alvorada',
          id_autor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 37,
          nome: 'A Cadeira de Prata',
          id_autor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 37,
          nome: 'A Última Batalha',
          id_autor: 35,
          tenho: 0,
          lido: 1,
          nota: 9,
          id_categoria: 3,
          id_editora: 15,
        },
        {
          id_colecao: 38,
          nome: 'A Cor da Magia',
          id_autor: 37,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 1,
          id_editora: 10,
        },
        {
          id_colecao: 1,
          nome: 'A Queda De Artur',
          id_autor: 1,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 1,
          nome: 'A Lenda de Sigurd e Gudrún',
          id_autor: 1,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 1,
          nome: 'Mestre Gil de Ham',
          id_autor: 1,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 1,
          nome: 'Roverandom',
          id_autor: 1,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 1,
          nome: 'Contos inacabados',
          id_autor: 1,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 1,
          nome: 'As Cartas de J. R. R. Tolkien',
          id_autor: 1,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 1,
          nome: 'O Silmarillion',
          id_autor: 1,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 1,
          nome: 'O Hobbit',
          id_autor: 1,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 1,
        },
        {
          id_colecao: 1,
          nome: 'Atlantis',
          id_autor: 26,
          tenho: 1,
          lido: 1,
          nota: 7,
          id_categoria: 2,
          id_editora: 11,
        },
        {
          id_colecao: 1,
          nome: 'O Coração Dos Heróis',
          id_autor: 25,
          tenho: 1,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 2,
        },
        {
          id_colecao: 1,
          nome: 'Jogador Nº 1',
          id_autor: 32,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 3,
          id_editora: 2,
        },
        {
          id_colecao: 1,
          nome: 'Ruas Estranhas',
          id_autor: 5,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 3,
          id_editora: 2,
        },
        {
          id_colecao: 1,
          nome: 'Os Pilares da Terra',
          id_autor: 33,
          tenho: 1,
          lido: 1,
          nota: 8,
          id_categoria: 2,
          id_editora: 8,
        },
        {
          id_colecao: 1,
          nome: 'Stonehenge',
          id_autor: 2,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 3,
        },
        {
          id_colecao: 1,
          nome: 'O Mundo Magico Do Senhor Dos Aneis',
          id_autor: 34,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 1,
          id_editora: 18,
        },
        {
          id_colecao: 1,
          nome: 'Os Filhos de Húrin',
          id_autor: 1,
          tenho: 1,
          lido: 1,
          nota: 9,
          id_categoria: 1,
          id_editora: 9,
        },
        {
          id_colecao: 1,
          nome: 'Fora de Controle',
          id_autor: 36,
          tenho: 0,
          lido: 0,
          nota: 0,
          id_categoria: 2,
          id_editora: 19,
        },
      ],
      {
        timestamps: false,
      }
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('livros', null, {});
  },
};
